language: minimal

services:
  - docker

script:
  - docker build -t fin1ger/simple-raft-node:example-helm -f examples/helm/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/simple-raft-node:example-helm
